import { StyleSheet } from 'react-native';
import historyScreen from './historyScreen';

export const colors = {
    grey: '#e1dddd',
    textGrey: '#b0b2b3',
    darkGrey: '#727676',
    white: '#fff',
    black: '#000',
    red: '#c30000',
    lightRed: '#ff303a',
    orange: '#ff7312',
    yellow: '#ffd800',
    blue: '#3b91fc',
    lightBlue: '#f0fbff',
    green: '#30c69f',
    lightGreen:'#00de65',
    navBarInactive: '#b9b9b9'
}

export const styles = StyleSheet.create({
    title: {
        fontWeight: '600',
        fontSize: 36,
        marginTop: 25,
        marginBottom: 2,
        textAlign: 'center',
    },
    subtitle: {
        fontSize: 18,
        color: 'grey',
        marginBottom: 15,
        textAlign: 'center',
    },
    sliderTrackStyle: {
        backgroundColor: colors.grey,
        height: 12,
        borderRadius: 20,
    },
    roundButtonM: {
        height: 60,
        width: 60,
        borderRadius: 30,
        padding: 0,
        alignSelf: 'center',
        backgroundColor: colors.white,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.25,
        shadowRadius: 4.84,
        elevation: 11,
    },
    roundButtonPaddingM: {
        height: 80,
        width: 80,
        padding: 7,
        // marginTop:10,
        alignSelf: 'center',
    },
    roundButtonS: {
        height: 40,
        width: 40,
        borderRadius: 20,
        padding: 0,
        alignSelf: 'center',
        backgroundColor: colors.white,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    roundButtonPaddingS: {
        height: 50,
        width: 50,
        padding: 2,
        // marginTop:10,
        alignSelf: 'center',
    },
    //   ********* historyScreen ********* 
    heading: {
        fontWeight: 'bold',
        fontSize: 36,
        color: colors.blue,
        marginTop: 70,
        marginBottom: 36,
        marginLeft: 26,
    },
    foodContainer: {
        width: '85%',
        height: '20%',
        alignSelf: 'center',
        backgroundColor: colors.white,
        borderTopLeftRadius: 12,
        borderTopRightRadius: 12,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 1,
        },
        zIndex: 1,
        shadowOpacity: 0.15,
        shadowRadius: 3.34,
        elevation: 4,
    },
    detailsContainer: {
        width: '85%',
        height: '10%',
        zIndex: 0,
        flexDirection: 'row',
        alignSelf: 'center',
        backgroundColor: colors.lightBlue,
        borderBottomLeftRadius: 12,
        borderBottomRightRadius: 12,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    foodCircle: {
        height: 45,
        width: 45,
        marginLeft: 14,
        marginTop: 15,
        borderRadius: 22,
        padding: 0,
        backgroundColor: colors.yellow,
    },
    foodCircleM: {
        height: 28,
        width: 28,
        marginTop: 26,
    },
    detailsCircle: {
        marginTop: 8,
        height: 22,
        width: 22,
    },
    detailText: {
        marginTop: 12,
        marginRight: 18,
        color: colors.darkGrey,
    },
    //  ********** profile screen *********
    profileCircle: {
        height: 65,
        width: 65,
        marginLeft: 52,
        borderRadius: 32,
        marginBottom:42,
        padding: 0,
        backgroundColor: colors.yellow,
    },
    fullName: {
        fontWeight: 'bold',
        marginLeft: 14,
        marginRight: 38,
        fontSize: 22
    },
    weekly: {
        fontWeight: '500',
        marginLeft: 44,
        marginRight: 38,
        fontSize: 22,
        width:'40%',
    },
    energy:{
        fontSize: 16,
        color: 'grey',
        marginBottom: 15,
        marginTop:6,
        textAlign:'right',
        width:'30%',
    },
    recomend: {
        height:'50%',
        width:'100%',
        backgroundColor: colors.yellow,
    },
    recomendContainer:{
        width:'50%',
        height:'50%',
        backgroundColor: colors.yellow,
        marginLeft:44,
    }
});
